
#这里只把feign做客户端用，不注册进eureka
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
spring:
  application:
    name: cloud-consumer-hystrix-payment
server:
  port: 81
#开启feign对hystrix的支持
feign:
  hystrix:
    enabled: true

#配置熔断的时间监听
#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          isolation:
#            thread:
#              timeoutInMilliseconds: 15000

#关闭hystrix时间检测功能
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

#暴露全部的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"
